=== 765741668/l2j_datapack/L2J_DataPack/dist/game/data/scripts/ai/npc/Teleports/teleporterData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="location" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:normalizedString" name="name" use="required" />
									<xs:attribute type="xs:positiveInteger" name="npcStringId" use="optional" />
									<xs:attribute type="xs:int" name="x" use="required" />
									<xs:attribute type="xs:int" name="y" use="required" />
									<xs:attribute type="xs:int" name="z" use="required" />
									<xs:attribute type="xs:int" name="heading" use="optional" />
									<xs:attribute type="xs:int" name="feeId" use="optional" />
									<xs:attribute type="xs:long" name="feeCount" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:int" name="id" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 765741668/l2j_datapack/L2J_DataPack/dist/game/data/scripts/ai/npc/Teleports/teleporterData.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="teleporterData.xsd">
	<npc id="30256"> <!-- Bella -->
		<location name="Town of Schuttgart" npcStringId="1010574" x="87130" y="-143514" z="-1291" feeCount="85000" />
		<location name="Heine" npcStringId="1010049" x="111453" y="219391" z="-3545" feeCount="47000" />
		<location name="Town of Aden" npcStringId="1010023" x="146798" y="25796" z="-2012" feeCount="56000" />
		<location name="Town of Oren" npcStringId="1010013" x="82958" y="53213" z="-1495" feeCount="35000" />
		<location name="The Town of Dion" npcStringId="1010006" x="15487" y="142871" z="-2701" feeCount="3400" />
		<location name="Town of Goddard" npcStringId="1010199" x="148015" y="-55293" z="-2733" feeCount="71000" />
		<location name="The Town of Giran" npcStringId="1010007" x="83551" y="147945" z="-3395" feeCount="29000" />
		<location name="Town of Rune" npcStringId="1010200" x="43823" y="-47760" z="-796" feeCount="53000" />
		<location name="The Village of Gludin" npcStringId="1010004" x="-80678" y="149769" z="-3043" feeCount="7300" />
		<location name="Talking Island Village" npcStringId="1010001" x="-113443" y="256656" z="-1504" feeCount="16000" />
		<location name="Elven Village" npcStringId="1010155" x="44730" y="49210" z="-3059" feeCount="9200" />
		<location name="Dark Elf Village" npcStringId="1010156" x="11162" y="16012" z="-4584" feeCount="10000" />
		<location name="Dwarven Village" npcStringId="1010158" x="115341" y="-178221" z="-928" feeCount="32000" />
		<location name="Orc Village" npcStringId="1010157" x="-44132" y="-113378" z="-238" feeCount="23000" />
		<location name="Kamael Village" npcStringId="1010648" x="-116977" y="46607" z="368" feeCount="12000" />
		<location name="Faeron Village" npcStringId="1010741" x="-80532" y="247714" z="-3492" feeCount="14000" />
		<location name="Windmill Hill (Lv. 20)" npcStringId="1010175" x="-74850" y="168753" z="-3506" feeCount="1400" />
		<location name="Ruins of Agony (Lv. 25)" npcStringId="1010097" x="-41167" y="122789" z="-2914" feeCount="790" />
		<location name="Ruins of Despair (Lv. 30)" npcStringId="1010101" x="-19353" y="136842" z="-3759" feeCount="610" />
		<location name="Wastelands (Lv. 35)" npcStringId="1010621" x="-16475" y="208815" z="-3662" feeCount="1400" />
		<location name="Ant Nest (Lv. 29)" npcStringId="1010566" x="-9965" y="176174" z="-4149" feeCount="2100" />
		<location name="Windawood Manor (Lv. 22)" npcStringId="1010102" x="-28341" y="155100" z="-3514" feeCount="1400" />
	</npc>
	<npc id="30320"> <!-- Rychlin -->
		<location name="The Town of Gludio" npcStringId="1010005" x="-14608" y="123920" z="-3128" feeCount="7300" />
		<location name="Talking Island Village" npcStringId="1010001" x="-113443" y="256656" z="-1504" feeCount="11000" />
		<location name="Elven Village" npcStringId="1010155" x="44730" y="49210" z="-3059" feeCount="16000" />
		<location name="Dark Elf Village" npcStringId="1010156" x="11162" y="16012" z="-4584" feeCount="16000" />
		<location name="Dwarven Village" npcStringId="1010158" x="115341" y="-178221" z="-928" feeCount="38000" />
		<location name="Orc Village" npcStringId="1010157" x="-44132" y="-113378" z="-238" feeCount="26000" />
		<location name="Kamael Village" npcStringId="1010648" x="-116977" y="46607" z="368" feeCount="10000" />
		<location name="Faeron Village" npcStringId="1010741" x="-80532" y="247714" z="-3492" feeCount="9700" />
		<location name="Langk Lizardmen Dwellings" npcStringId="1010100" x="-44770" y="203488" z="-3592" feeCount="1800" />
		<location name="Windmill Hill" npcStringId="1010175" x="-74850" y="168753" z="-3506" feeCount="550" />
		<location name="Fellmere Harvesting Grounds" npcStringId="1010096" x="-63736" y="101511" z="-3554" feeCount="1400" />
		<location name="Forgotten Temple" npcStringId="1010106" x="-53008" y="191421" z="-3571" feeCount="2000" />
		<location name="Orc Barracks" npcStringId="1010095" x="-89776" y="105344" z="-3581" feeCount="1800" />
		<location name="Windy Hill" npcStringId="1010094" x="-93421" y="89616" z="-3219" feeCount="2600" />
		<location name="Wastelands" npcStringId="1010621" x="-16475" y="208815" z="-3662" feeCount="3400" />
		<location name="Red Rock Ridge" npcStringId="1010176" x="-42264" y="198323" z="-2806" feeCount="3700" />
		<location name="Ruins of Agony" npcStringId="1010097" x="-41167" y="122789" z="-2914" feeCount="1900" />
		<location name="Isle of Souls Harbor" npcStringId="1010652" x="-73991" y="51929" z="-3680" feeCount="15000" />
		<location name="Ruins of Despair" npcStringId="1010101" x="-19353" y="136842" z="-3759" feeCount="2500" />
	</npc>
</list>

=== 765741668/l2j_datapack/L2J_DataPack/dist/game/data/teleporters/Trisha.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/teleporterData.xsd">
	<npc id="30059"> <!-- Trisha -->
		<teleport type="NORMAL">
			<location npcStringId="1010007" x="83551" y="147945" z="-3395" feeCount="6800" /> <!-- The town of Giran -->
			<location npcStringId="1010049" x="111453" y="219391" z="-3545" feeCount="12000" /> <!-- Heine -->
			<location npcStringId="1010005" x="-14608" y="123920" z="-3128" feeCount="3400" /> <!-- The Town of Gludio -->
			<location npcStringId="1010199" x="148015" y="-55293" z="-2733" feeCount="71000" /> <!-- Town of Goddard -->
			<location npcStringId="1010200" x="43823" y="-47760" z="-796" feeCount="57000" /> <!-- Town of Rune -->
			<location npcStringId="1010574" x="87130" y="-143514" z="-1291" feeCount="88000" /> <!-- Town of Schuttgart -->
			<location npcStringId="1010023" x="146798" y="25796" z="-2012" feeCount="52000" /> <!-- Town of Aden -->
			<location npcStringId="1010013" x="82958" y="53213" z="-1495" feeCount="33000" /> <!-- Town of Oren -->
			<location npcStringId="1010001" x="-113443" y="256656" z="-1504" feeCount="17000" /> <!-- Talking Island Village -->
			<location npcStringId="1010614" x="5106" y="126916" z="-3659" feeCount="760" /> <!-- Cruma Marshlands -->
			<location npcStringId="1010116" x="17232" y="114186" z="-3439" feeCount="2300" /> <!-- Cruma Tower -->
			<location npcStringId="1010113" x="47382" y="111278" z="-2099" feeCount="1700" /> <!-- Fortress of Resistance -->
			<location npcStringId="1010111" x="545" y="179163" z="-3425" feeCount="1500" /> <!-- Plains of Dion -->
			<location npcStringId="1010599" x="34475" y="188095" z="-2971" feeCount="2900" /> <!-- Bee Hive -->
			<location npcStringId="1010115" x="60374" y="164301" z="-2851" feeCount="3900" /> <!-- Tanor Canyon -->
		</teleport>
		<teleport type="NOBLES_TOKEN">
			<!-- TODO: done me -->
		</teleport>
		<teleport type="NOBLES_ADENA">
			<!-- TODO: done me -->
		</teleport>
	</npc>
</list>
